-- ==========================================
-- STEP 1: UPLOAD THE 50 PRODUCTS TO SERVERS 
-- ==========================================
-- Copy and paste this entirely into your Supabase SQL Editor and click "RUN".

INSERT INTO public.products (id, title, slug, description, price, vendor_id, status, featured, thumbnail_url, version, tags, sales_count) VALUES
('1', 'Startup Template 1', 'startup-template-1', 'High-converting landing page template optimized for speed and SEO. Features smooth animations and responsive design.', 44, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', true, '/assets/placeholders/landing_pages_scene_2.png', '3.9.0', ARRAY['landingpages','premium','digital'], 1860),
('2', 'Chat Flutter Template 1', 'chat-flutter-template-1', 'Production-ready mobile application template. Cross-platform support with clean architecture and state management.', 39, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', true, '/assets/placeholders/mobile_apps.png', '1.8.0', ARRAY['mobileapps','premium','digital'], 1710),
('3', 'Project Web App 4', 'project-web-app-4', 'Feature-rich admin dashboard theme with charts, tables, and authentications screens. Dark mode included.', 83, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', true, '/assets/placeholders/dashboard_themes_scene_1.png', '5.3.0', ARRAY['dashboardthemes','premium','digital'], 3179),
('4', 'Premium Vectors 5', 'premium-vectors-5', 'Carefully crafted vector graphics and icons. Fully customizable shapes available in multiple formats (SVG, PNG, Figma).', 83, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', true, '/assets/placeholders/icons_graphics_scene_2.png', '5.9.0', ARRAY['icons&graphics','premium','digital'], 4524),
('5', 'Payment Module 1', 'payment-module-1', 'Scalable backend solution. Well-documented codebase with tests, CI/CD setup, and database schemas.', 84, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', true, '/assets/placeholders/backend_code.png', '1.4.0', ARRAY['backendcode','premium','digital'], 3830),
('6', 'Neo Components 5', 'neo-components-5', 'A comprehensive UI kit built with modern design principles. Includes hundreds of components, auto-layout support, and global styles.', 81, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', true, '/assets/placeholders/ui_kits_scene_1.png', '3.7.0', ARRAY['uikits','premium','digital'], 103),
('7', 'Agency Promo Page 8', 'agency-promo-page-8', 'High-converting landing page template optimized for speed and SEO. Features smooth animations and responsive design.', 41, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', true, '/assets/placeholders/landing_pages_scene_2.png', '5.3.0', ARRAY['landingpages','premium','digital'], 458),
('8', 'Chat Flutter Template 9', 'chat-flutter-template-9', 'Production-ready mobile application template. Cross-platform support with clean architecture and state management.', 48, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', true, '/assets/placeholders/mobile_apps_scene_2.png', '4.1.0', ARRAY['mobileapps','premium','digital'], 2174),
('9', 'Sales Panel 5', 'sales-panel-5', 'Feature-rich admin dashboard theme with charts, tables, and authentications screens. Dark mode included.', 36, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/dashboard_themes_scene_1.png', '4.1.0', ARRAY['dashboardthemes','premium','digital'], 3283),
('10', 'Solid Icons 9', 'solid-icons-9', 'Carefully crafted vector graphics and icons. Fully customizable shapes available in multiple formats (SVG, PNG, Figma).', 76, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/icons_graphics_scene_2.png', '3.0.0', ARRAY['icons&graphics','premium','digital'], 1231),
('11', 'Payment Module 2', 'payment-module-2', 'Scalable backend solution. Well-documented codebase with tests, CI/CD setup, and database schemas.', 39, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/backend_code.png', '3.9.0', ARRAY['backendcode','premium','digital'], 4578),
('12', 'Ultra UI 9', 'ultra-ui-9', 'A comprehensive UI kit built with modern design principles. Includes hundreds of components, auto-layout support, and global styles.', 35, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/ui_kits_scene_1.png', '3.1.0', ARRAY['uikits','premium','digital'], 1539),
('13', 'Product Landing 1', 'product-landing-1', 'High-converting landing page template optimized for speed and SEO. Features smooth animations and responsive design.', 86, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/landing_pages_scene_1.png', '2.7.0', ARRAY['landingpages','premium','digital'], 222),
('14', 'Delivery React Native Kit 3', 'delivery-react-native-kit-3', 'Production-ready mobile application template. Cross-platform support with clean architecture and state management.', 36, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/mobile_apps_scene_1.png', '2.0.0', ARRAY['mobileapps','premium','digital'], 338),
('15', 'Crypto Dashboard 3', 'crypto-dashboard-3', 'Feature-rich admin dashboard theme with charts, tables, and authentications screens. Dark mode included.', 82, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/dashboard_themes.png', '3.3.0', ARRAY['dashboardthemes','premium','digital'], 182),
('16', 'Premium Vectors 9', 'premium-vectors-9', 'Carefully crafted vector graphics and icons. Fully customizable shapes available in multiple formats (SVG, PNG, Figma).', 58, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/icons_graphics.png', '1.0.0', ARRAY['icons&graphics','premium','digital'], 107),
('17', 'GraphQL API 4', 'graphql-api-4', 'Scalable backend solution. Well-documented codebase with tests, CI/CD setup, and database schemas.', 19, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/backend_code_scene_1.png', '1.4.0', ARRAY['backendcode','premium','digital'], 3492),
('18', 'Ultra Design System 9', 'ultra-design-system-9', 'A comprehensive UI kit built with modern design principles. Includes hundreds of components, auto-layout support, and global styles.', 79, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/ui_kits.png', '2.4.0', ARRAY['uikits','premium','digital'], 4658),
('19', 'SaaS Landing 3', 'saas-landing-3', 'High-converting landing page template optimized for speed and SEO. Features smooth animations and responsive design.', 25, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/landing_pages_scene_1.png', '2.9.0', ARRAY['landingpages','premium','digital'], 2504),
('20', 'Fitness App UI 2', 'fitness-app-ui-2', 'Production-ready mobile application template. Cross-platform support with clean architecture and state management.', 50, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/mobile_apps_scene_1.png', '2.8.0', ARRAY['mobileapps','premium','digital'], 395),
('21', 'Admin Panel 7', 'admin-panel-7', 'Feature-rich admin dashboard theme with charts, tables, and authentications screens. Dark mode included.', 53, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/dashboard_themes.png', '2.0.0', ARRAY['dashboardthemes','premium','digital'], 2791),
('22', 'Premium Illustration Pack 1', 'premium-illustration-pack-1', 'Carefully crafted vector graphics and icons. Fully customizable shapes available in multiple formats (SVG, PNG, Figma).', 39, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/icons_graphics_scene_1.png', '2.3.0', ARRAY['icons&graphics','premium','digital'], 485),
('23', 'GraphQL Microservice 3', 'graphql-microservice-3', 'Scalable backend solution. Well-documented codebase with tests, CI/CD setup, and database schemas.', 21, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/backend_code.png', '1.5.0', ARRAY['backendcode','premium','digital'], 2347),
('24', 'Pro Design System 7', 'pro-design-system-7', 'A comprehensive UI kit built with modern design principles. Includes hundreds of components, auto-layout support, and global styles.', 33, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/ui_kits.png', '2.1.0', ARRAY['uikits','premium','digital'], 176),
('25', 'App Waitlist 9', 'app-waitlist-9', 'High-converting landing page template optimized for speed and SEO. Features smooth animations and responsive design.', 95, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/landing_pages.png', '5.6.0', ARRAY['landingpages','premium','digital'], 716),
('26', 'Chat Mobile Kit 1', 'chat-mobile-kit-1', 'Production-ready mobile application template. Cross-platform support with clean architecture and state management.', 61, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/mobile_apps.png', '3.3.0', ARRAY['mobileapps','premium','digital'], 4754),
('27', 'Analytics Admin Template 4', 'analytics-admin-template-4', 'Feature-rich admin dashboard theme with charts, tables, and authentications screens. Dark mode included.', 99, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/dashboard_themes.png', '4.7.0', ARRAY['dashboardthemes','premium','digital'], 4956),
('28', 'Solid Icons 4', 'solid-icons-4', 'Carefully crafted vector graphics and icons. Fully customizable shapes available in multiple formats (SVG, PNG, Figma).', 98, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/icons_graphics_scene_2.png', '4.6.0', ARRAY['icons&graphics','premium','digital'], 1246),
('29', 'Auth Microservice 8', 'auth-microservice-8', 'Scalable backend solution. Well-documented codebase with tests, CI/CD setup, and database schemas.', 43, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/backend_code.png', '3.2.0', ARRAY['backendcode','premium','digital'], 3387),
('30', 'Neo Components 1', 'neo-components-1', 'A comprehensive UI kit built with modern design principles. Includes hundreds of components, auto-layout support, and global styles.', 50, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/ui_kits_scene_1.png', '4.6.0', ARRAY['uikits','premium','digital'], 1867),
('31', 'Product Template 6', 'product-template-6', 'High-converting landing page template optimized for speed and SEO. Features smooth animations and responsive design.', 50, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/landing_pages_scene_2.png', '3.8.0', ARRAY['landingpages','premium','digital'], 1064),
('32', 'Fitness Mobile Kit 3', 'fitness-mobile-kit-3', 'Production-ready mobile application template. Cross-platform support with clean architecture and state management.', 63, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/mobile_apps_scene_2.png', '4.3.0', ARRAY['mobileapps','premium','digital'], 3087),
('33', 'Crypto Panel 1', 'crypto-panel-1', 'Feature-rich admin dashboard theme with charts, tables, and authentications screens. Dark mode included.', 93, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/dashboard_themes.png', '5.1.0', ARRAY['dashboardthemes','premium','digital'], 2222),
('34', 'Solid Shapes 2', 'solid-shapes-2', 'Carefully crafted vector graphics and icons. Fully customizable shapes available in multiple formats (SVG, PNG, Figma).', 88, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/icons_graphics.png', '3.9.0', ARRAY['icons&graphics','premium','digital'], 604),
('35', 'GraphQL Boilerplate 8', 'graphql-boilerplate-8', 'Scalable backend solution. Well-documented codebase with tests, CI/CD setup, and database schemas.', 51, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/backend_code_scene_1.png', '4.7.0', ARRAY['backendcode','premium','digital'], 345),
('36', 'Neo Design System 1', 'neo-design-system-1', 'A comprehensive UI kit built with modern design principles. Includes hundreds of components, auto-layout support, and global styles.', 68, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/ui_kits_scene_2.png', '1.0.0', ARRAY['uikits','premium','digital'], 3172),
('37', 'Startup Promo Page 6', 'startup-promo-page-6', 'High-converting landing page template optimized for speed and SEO. Features smooth animations and responsive design.', 62, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/landing_pages_scene_1.png', '4.5.0', ARRAY['landingpages','premium','digital'], 3666),
('38', 'Social App UI 1', 'social-app-ui-1', 'Production-ready mobile application template. Cross-platform support with clean architecture and state management.', 83, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/mobile_apps.png', '1.3.0', ARRAY['mobileapps','premium','digital'], 3417),
('39', 'Crypto Dashboard 1', 'crypto-dashboard-1', 'Feature-rich admin dashboard theme with charts, tables, and authentications screens. Dark mode included.', 59, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/dashboard_themes.png', '2.4.0', ARRAY['dashboardthemes','premium','digital'], 1270),
('40', 'Duotone Icons 3', 'duotone-icons-3', 'Carefully crafted vector graphics and icons. Fully customizable shapes available in multiple formats (SVG, PNG, Figma).', 37, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/icons_graphics_scene_1.png', '1.4.0', ARRAY['icons&graphics','premium','digital'], 2461),
('41', 'Socket Microservice 9', 'socket-microservice-9', 'Scalable backend solution. Well-documented codebase with tests, CI/CD setup, and database schemas.', 32, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/backend_code_scene_1.png', '1.4.0', ARRAY['backendcode','premium','digital'], 3185),
('42', 'Pro Design System 2', 'pro-design-system-2', 'A comprehensive UI kit built with modern design principles. Includes hundreds of components, auto-layout support, and global styles.', 79, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/ui_kits_scene_1.png', '2.1.0', ARRAY['uikits','premium','digital'], 4068),
('43', 'Startup Promo Page 9', 'startup-promo-page-9', 'High-converting landing page template optimized for speed and SEO. Features smooth animations and responsive design.', 32, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/landing_pages.png', '4.9.0', ARRAY['landingpages','premium','digital'], 2710),
('44', 'Finance React Native Kit 4', 'finance-react-native-kit-4', 'Production-ready mobile application template. Cross-platform support with clean architecture and state management.', 85, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/mobile_apps.png', '2.5.0', ARRAY['mobileapps','premium','digital'], 376),
('45', 'Crypto Panel 1', 'crypto-panel-1', 'Feature-rich admin dashboard theme with charts, tables, and authentications screens. Dark mode included.', 88, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/dashboard_themes_scene_1.png', '3.4.0', ARRAY['dashboardthemes','premium','digital'], 657),
('46', 'Duotone Vectors 6', 'duotone-vectors-6', 'Carefully crafted vector graphics and icons. Fully customizable shapes available in multiple formats (SVG, PNG, Figma).', 77, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/icons_graphics_scene_2.png', '1.9.0', ARRAY['icons&graphics','premium','digital'], 1662),
('47', 'Auth API 2', 'auth-api-2', 'Scalable backend solution. Well-documented codebase with tests, CI/CD setup, and database schemas.', 41, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/backend_code.png', '3.4.0', ARRAY['backendcode','premium','digital'], 899),
('48', 'Neo Interface Kit 1', 'neo-interface-kit-1', 'A comprehensive UI kit built with modern design principles. Includes hundreds of components, auto-layout support, and global styles.', 30, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/ui_kits_scene_2.png', '1.7.0', ARRAY['uikits','premium','digital'], 548),
('49', 'Agency Landing 3', 'agency-landing-3', 'High-converting landing page template optimized for speed and SEO. Features smooth animations and responsive design.', 68, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/landing_pages.png', '5.6.0', ARRAY['landingpages','premium','digital'], 3685),
('50', 'Chat Mobile Kit 8', 'chat-mobile-kit-8', 'Production-ready mobile application template. Cross-platform support with clean architecture and state management.', 35, '888b6182-eac0-485a-8d54-e881dec139d2', 'approved', false, '/assets/placeholders/mobile_apps_scene_2.png', '3.3.0', ARRAY['mobileapps','premium','digital'], 1550);

-- ==========================================
-- STEP 2: HOW TO GET YOUR ADMIN PASSWORD  
-- ==========================================
-- Because Supabase heavily encrypts passwords, you cannot extract the default admin password.
-- Instead, follow these 3 steps to make YOUR OWN account the Admin:
-- 1. Go to your live website and "Sign Up" normally with your own Email and Password.
-- 2. Go to your Supabase Dashboard -> Authentication -> Users, and copy the 'User UID' of the account you just made.
-- 3. Paste your User UID into the command below and RUN it in the SQL Editor to grant yourself full Admin access:

-- INSERT INTO public.user_roles (user_id, role) VALUES ('PASTE-YOUR-UID-HERE', 'admin') ON CONFLICT (user_id, role) DO UPDATE SET role = 'admin';
